In [1]:
import pandas as pd
import numpy as np

In [32]:
# Reading csv file
df = pd.read_csv('data.csv')

data = df.iloc[:,[1,2,3]].values
date = df.iloc[:,[0]].values
store = data[:,1]
item = data[:,2]

In [33]:
store_id = set(store)
item_id = set(item)

In [34]:
print(data)

[[ 6 29 78]
 [ 7 21 32]
 [ 8 38 86]
 ...
 [ 9 17 54]
 [ 7 20 50]
 [ 2  4 32]]


In [24]:
month = ['-01-','-02-','-03-','-04-','-05-','-06-'
        ,'-07-','-08-','-09-','-10-','-11-','-12-']

In [37]:
m = []
for i in range(date.shape[0]):
    for j in range(len(month)):
        m.append((j+1,data[i]))

In [46]:
m = np.array(m)
print(m[0])

[1 array([ 6, 29, 78])]


In [52]:
sale = []
for i in range(12):
    for j in range(10):
        for k in range(50):
            s=0
            for l in range(m.shape[0]):
                if(m[l][0] == i+1 and m[l][1][0] == j+1 and m[l][1][1] == k+1):
                    s+=m[l][1][2]
            sale.append((i+1,j+1,k+1,s))

In [56]:
sale = np.array(sale)
print(sale.shape)
print(sale)

(6000, 4)
[[   1    1    1  296]
 [   1    1    2  438]
 [   1    1    3  300]
 ...
 [  12   10   48  556]
 [  12   10   49  226]
 [  12   10   50 1183]]


In [57]:
pd.DataFrame(sale).to_csv("sale_data.csv",header=['month','store_id','item_id','sale'],index=False)

In [63]:
print(sale[1])

[  1   1   2 438]


In [64]:
store_1 = []
for i in range(sale.shape[0]):
    if (sale[i][1] == 1):
        store_1.append((sale[i][0],sale[i][2],sale[i][3]))
        
store_1 = np.array(store_1)

In [82]:
print(store_1[60][0])

2


In [83]:
store1 = []
for i in range(12):
    s=0
    for j in range(store_1.shape[0]):
        if(store_1[j][0]==(i+1)):
            s+=store_1[i][2]
    store1.append(s)

In [84]:
store1 = np.array(store1)
print(store1)

[14800 21900 15000  7500 10750 44400 30800 47200 20100 33350 51100 44650]


In [93]:
store1_data = []
for i in range(12):
    for j in range(store_1.shape[0]):
        if(store_1[j][0]==(i+1)):
            store1_data.append((int(store_1[j][0]),int(store_1[j][1]),int(store_1[j][2]),"{:.2f}".format(store_1[j][2]/store1[i])))
store1_data = np.array(store1_data)

In [99]:
print(store1_data.shape)

(600, 4)


In [95]:
pd.DataFrame(store1_data).to_csv("store1_data.csv",header=['month','item_id','sale','sale_per_month'],index=False)

In [96]:
stock = np.random.randint(800,2000,size=600)
r_shelf_time = np.random.randint(1,10,size=600)

In [100]:
print(stock.shape)
print(r_shelf_time.shape)

(600,)
(600,)


In [103]:
df = pd.read_csv('store1_data.csv')
df['stock'] = stock
df['r_shelf_time'] = r_shelf_time
df.to_csv('store_data.csv',index=False)

In [122]:
sale = np.array(store1_data[:,3],dtype='float64')

In [118]:
discount = []
for i in range(600):
    if(sale[i]*stock[i] < r_shelf_time[i]):
        discount.append(0)
    elif(sale[i]*stock[i] > 2*r_shelf_time[i]):
        discount.append(60)
    elif(sale[i]*stock[i] > r_shelf_time[i]):
        discount.append(40)

In [121]:
discount = np.array(discount)
print(discount)

[60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 40 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60 60 40 60 60 60 60 60 60 60 60 60 60 60 60 40 60 60 60 60 60 60
 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60 60 60 60 60 40 40 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 40 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
 60 60 60 60 60 60 60 60 60 60 40 40 60  0  0 60 60 60 60 60 60 60 60 60
 60 60  0 60 60 60 60 60 40 60 60 60  0 60 60 60 60 60 60 60 60 40 40 40
 60 60  0  0 60 60 40 60 60 40 40 60 60 40 60  0 60 60 60 60 60 60 60 60
 60 40 60 60  0 60 60 60 40 60 60 60 60 60 40 60 40

In [123]:
df = pd.read_csv('store1_data.csv')
df.drop('sale_per_month',inplace=True, axis=1)
df['sale_per_month'] = sale
df['stock'] = stock
df['r_shelf_time'] = r_shelf_time
df['discount'] = discount
df.to_csv('warehouse_data.csv',index=False)